[package]
name = "midi2miracle"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
midir = "0.9.1"
anyhow = "1.0.71"
midly = "0.5.3"